### ISSUE TITLE
Call to action that has external link or downloadable PDF has incorrect hover state

### ISSUE THREAD

**Issue by stephanieosan** [cfpb/design-system#1070]
## Bug

If a call to action button is given a URL that is an external link or a downloadable PDF, it will get an external link or a download icon next to the button text. An example page of both of these is:
https://www.consumerfinance.gov/about-us/blog/buying-home-first-step-check-your-credit/

The problem is when hovering over the button, the button gets both a highlight and an underline:

<img width="316" alt="Screen Shot 2020-10-02 at 10 58 32 AM" src="https://user-images.githubusercontent.com/6433178/94937958-43934180-049e-11eb-9220-e258cbe25ed8.png">

Which differs from how other call to action button hover states appear:

<img width="372" alt="Screen Shot 2020-10-02 at 10 59 31 AM" src="https://user-images.githubusercontent.com/6433178/94938077-6291d380-049e-11eb-8353-38d5ae0fb121.png">

### Desired state
* When hovered over, buttons with an external or download icon have no underlines.
* We may want to add these types of buttons to the Design System as examples of icon buttons, too.

**Comment by anselmbradford** [comment]
This is a backend issue, right @chosak ? The code that auto-adds the icon needs to account for this button case.

**Comment by chosak** [comment]
@anselmbradford it looks to me like this is happening:

- `a-btn` assigns `color: #ffffff`
- `a:hover` assigns `border-style: solid` (to add the solid button border on hover)
- `a-link_text` assigns `border-bottom-style: inherit` <-- this generates the white bottom border for the text span

We could add something like `.a-btn .a-link_text { border-bottom-style: none }` if there's some reason to keep `.a-link_text` here. Or are you suggesting that links within buttons like this shouldn't get wrapped in an `.a-link_text` span at all?

**Comment by anselmbradford** [comment]
> Or are you suggesting that links within buttons like this shouldn't get wrapped in an .a-link_text span at all?

Yea this. The external/pdf button link classes are pretty frankensteinian

```
<a class="a-btn a-btn__full-on-xs a-link a-link__icon"  …>
  <span class="a-link_text">
```

Compare that to the rss button:

```
<a class="a-btn" …>
  <span class="a-btn_icon__on-left">
```

It seems like we should consistently architect button links that have icons instead of hacking around fixes for amalgamations of buttons and links.

**Comment by chosak** [comment]
@anselmbradford what would the proposed HTML look like, then? In [the relevant cf.gov code](https://github.com/cfpb/consumerfinance.gov/blob/46a7b9463d72b903c028ede7c193f25d4e3bfbe6/cfgov/core/utils.py#L172-L189), we always add the icon by wrapping an `<a>` link text in a `<span>` and then giving it a sibling `<svg>`.

**Comment by anselmbradford** [comment]
> what would the proposed HTML look like, then? In the relevant cf.gov code, we always add the icon by wrapping an <a> link text in a <span> and then giving it a sibling <svg>.

I'd think it should either match the left-hand icon markup of the rss button or the right-hand icon button used for the "edit page" button in DS.

**Comment by chosak** [comment]
Thanks,  @anselmbradford, if I understand correctly, instead of just correcting the hover state, this would be a new design for these buttons, something like:

|Left|Right|
|-|-|
|![image](https://user-images.githubusercontent.com/654645/96302507-f3040400-0fc6-11eb-9976-ba51961ea65e.png)|![image](https://user-images.githubusercontent.com/654645/96302410-c51ebf80-0fc6-11eb-9658-4817648ac226.png)|
|![image](https://user-images.githubusercontent.com/654645/96302879-81788580-0fc7-11eb-8da2-c5de1f65dca0.png)|![image](https://user-images.githubusercontent.com/654645/96302822-686fd480-0fc7-11eb-8c48-7866ae38f90e.png)|

Is there anything more targeted we can or want to do for the hover state given the current design? Or should we broaden this issue to instead be about a new design, and then implement in cf.gov once that's decided? @stephanieosan

**Comment by anselmbradford** [comment]
Yeah those buttons look like what I think they should look like.

**Comment by chosak** [comment]
Paging @huetingj -- any preference/thoughts on these? Personally I think the download looks nice both before and after but the external link should definitely come after -- not sure how/if that distinction can or should be encoded in the design system. Maybe we support two different variations, and implementations can use whichever one best fits any particular icon?

**Comment by huetingj** [comment]
Thanks for tagging me @chosak! 

Yahhhh, looks like we're pretty inconsistent regarding placement right now. The [DS guidance](https://cfpb.github.io/design-system/components/buttons#buttons-with-icons) says that icons should appear to the left of the button text. But closely below this guidance, we have a button example with an animated icon on the right, and the "Show all details" and "Edit page" buttons in the DS itself have the icon on the right. 

I definitely agree that if we have a button with an external link, it should be to the right of the text. (Side pondering: do we have any instances of an external link button on the site right now?) It makes sense to me in general to follow our placement of icons next to links, which as a standard is to have the icon on the right. (Although, I just looked at our DS links page and noticed that we state you can [place the icon prior to or after the link text](https://cfpb.github.io/design-system/components/links#links-with-icons-1), hmm. Maybe we should revise that, as I'm not sure of a use case needing the icon placed on the left. 🤔 )

I vote for always placing the icon to the right, except of course with a back/pagination button, which should be on the left. I realize this would involve changing the RSS button to have the icon on the right. Does anyone have insight regarding why the icon was originally placed on the left and any problems that might pop up if we switch it? Seems to me like it would be fine/pretty straight-forward design-wise to switch it. And does anyone know of any other buttons with icons on the left on the site? I just browsed [briefly] and didn't find any.

We could, as @chosak mentioned, move forward with giving the option of right or left. I'm OK with that, but I do think it'd be nice to choose one if possible. I'm not sure what reasoning would warrant someone to decide to place a button on the left instead of right (except of course when it's a pagination back arrow icon).

**Comment by chosak** [comment]
> do we have any instances of an external link button on the site right now?

 The "Sign up" button on [this blog post](https://www.consumerfinance.gov/about-us/blog/buying-home-first-step-check-your-credit/) points to govdelivery.com so it becomes an external link button.

> place a button on the left instead of right

One long-term consideration would be for languages that are read right-to-left ([for example](https://www.consumerfinance.gov/language/ar/)), although this is certainly not the only place where our design standards might need alteration.

**Comment by huetingj** [comment]
We talked about this during team time and decided to move forward with having an icon always appear after the text it represents, with the exception of the back button. This guidance holds true for languages that read right-to-left in that the icon will still appear after the text (it just will appear on the left rather than on the right in English). We discussed how this decision will require the RSS button's icon/text order to change, and we're OK with that. 

@anselmbradford if you could take care of this change in the code, that'd be great. I'll update the guidance on the DS button and link pages to reflect this decision. Thanks!

**Comment by anselmbradford** [comment]
@chosak I think this is all good in the DS and just needs implementing in cf.gov code that injects the icons.

**Comment by chosak** [comment]
Opened draft PR at https://github.com/cfpb/consumerfinance.gov/pull/6652.
