### ISSUE TITLE
[Enhancement] Add missing specs to links page

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/design-system#1711]
Add missing specs to the links page including: 
- Hex values for link states (throughout)
- Specs for call-to-action link
- Simplified styling for destructive link

### Inline links
- Added the hex values so that what a designer sees in code (inspector) matches what's in the specs. 

| Current | Update |  
|------------| ------------|
|![Screenshot 2023-08-14 at 2 23 54 PM](https://github.com/cfpb/design-system/assets/77348967/279bc1f0-c044-41df-915f-e392ba1d859c)|![Screenshot 2023-08-14 at 2 35 13 PM](https://github.com/cfpb/design-system/assets/77348967/42b8fe8c-d89f-4e73-a988-d46fe21b78f9)|

### Call-to-action links
- No current specs existed. 
- Consideration: Should we cross link between call-to-action links and list links? Are they the same thing? 

| Current (no specs) | Update |  
|------------| ------------|
|![Screenshot 2023-08-14 at 2 36 20 PM](https://github.com/cfpb/design-system/assets/77348967/9fb8f4d9-6645-4c52-a72f-7a87adfde87b)|![Screenshot 2023-08-14 at 3 17 24 PM](https://github.com/cfpb/design-system/assets/77348967/f5c98bce-84d0-42de-8a78-558d6539cfea)|

### Destructive links
- Optional: Add styling info for states
- Bug: Implementation tab is showing even though it contains no content

| Current | Update |  
|------------| ------------|
|![Screenshot 2023-08-14 at 2 36 25 PM](https://github.com/cfpb/design-system/assets/77348967/fdb6c685-3709-46be-9ca0-967406424f11)|![Screenshot 2023-08-14 at 2 35 33 PM](https://github.com/cfpb/design-system/assets/77348967/6a9dcf91-dea1-4f65-8a11-1cb8bf2086f5)|

Looking for review (optional): @meissadia @anselmbradford @jenn-franklin @chaisamantha

**Comment by chaisamantha** [comment]
Thanks for updating and adding specs! Here are some thoughts: 

**General**: Love the addition of hex codes next to color names. Would it be helpful to write specs that follow CSS formatting? So, instead of _1px dotted bottom border_, it would be _border-bottom: 1px dotted Pacific Blue (#0072ce)_. The updated call-to-action specs uses similar formatting. For focus states, it would be _outline: thin dotted_ instead of _thin dotted outline_.

**Call-to-action links**: For _When links appear as a part of a list_ section, I think it would be helpful to also add an image that helps visualize the specs between items. Here is a quick mockup: 

![Call-to-action spec visual](https://github.com/cfpb/design-system/assets/109407649/fb36ca00-bef2-4240-b140-d15c970bd44a)

**Destructive links**: I think it’d be helpful to include the font weight and size because destructive links aren’t grouped with call-to-action links.

**Comment by natalia-fitzgerald** [comment]
Ok here's a start on those updates: 

### Inline links
- Added the formatting identifiers to more closely align with CSS properties (see note below). 

| R1 | R2 |  
|------------| ------------|
|![Screenshot 2023-08-14 at 2 35 13 PM](https://github.com/cfpb/design-system/assets/77348967/42b8fe8c-d89f-4e73-a988-d46fe21b78f9)|![Screenshot 2023-08-14 at 4 43 37 PM](https://github.com/cfpb/design-system/assets/77348967/54b57a45-1348-4556-bac9-b068bc29af1c)|

### Destructive links
- Added font weight and size

| R1 | R2 |  
|------------| ------------|
|![Screenshot 2023-08-14 at 2 35 33 PM](https://github.com/cfpb/design-system/assets/77348967/6a9dcf91-dea1-4f65-8a11-1cb8bf2086f5)|![Screenshot 2023-08-14 at 4 56 47 PM](https://github.com/cfpb/design-system/assets/77348967/a116e996-0d0b-4e70-b461-69c556950a81)|

If we were to actually add the specs as they appear in the CSS we would actually break it up a lot more than what is described [here](https://github.com/cfpb/design-system/issues/1711#issuecomment-1677980340). I think this is worth discussing as a more global item. How do we want to format specs? Should the properties be labeled and ordered as they appear in CSS? 

The link styling includes all of these properties (and more): 
- Font-family
- Font-weight
- Font-size: 
- Color: 
- Border-width
- Border-style:
- Border-color: 
- Outline: 

I'll open up another issue to discuss the specs styling more globally. For now I'd like to go ahead and push these iterative updates.

**Comment by natalia-fitzgerald** [comment]
Closing this out because I have updated and published the specs on the links page. I will open a separate discussion issue regarding the way we write UI specs.
