### ISSUE TITLE
Notifications get extra bottom margin on narrow screens

### ISSUE THREAD

**Issue by chosak** [cfpb/design-system#1952]
I noticed today that notifications get a little extra bottom margin on narrow screens, [for example](https://www.consumerfinance.gov/about-us/blog/?title=&categories=at-the-cfpb&from_date=&to_date=):

<img width="1212" alt="image" src="https://github.com/cfpb/design-system/assets/654645/b3992438-8ee1-48de-bfaf-b878a92db2ed">

The `m-notification_message` class is applying [this margin](https://github.com/cfpb/design-system/blob/60c0d638347bc7ae9612ac155b79249c8dc48896/packages/cfpb-core/src/base.less#L258) from the h4 style even though the notification style itself specifies [no bottom margin](https://github.com/cfpb/design-system/blob/60c0d638347bc7ae9612ac155b79249c8dc48896/packages/cfpb-notifications/src/molecules/notification.less#L65).

I notice a recent commit from @anselmbradford in https://github.com/cfpb/design-system/pull/1940 that touched this. I'm not certain the right way to fix.

@sonnakim for awareness

**Comment by anselmbradford** [comment]
Good catch @chosak ! 

So, this is interesting. I'd think having the `h4` in the markup and as a mixin would be equivalent. But in this case it is not!
The reason is the order in which we load the design-system packages. The `h4` styles appear in `cfpb-core`, while the `m-notification` styles appear in `cfpb-notification`. `cfpb-core` is loaded first [here](https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/unprocessed/css/main.less#L10). If we swap the order and add the `h4` class, the `bottom-margin` will appear too! This is further evidence to me that it is the right choice to have these mixins directly in the classes themselves, versus mixing them in via markup, since mixed in via markup the import order will matter if the classes appear in different packages! (This is also probably evidence that we should move to one package and pull all our imports out of that.)

With the mixin moved to the CSS (from #1940), the problem here is the 0 margin-bottom override appears on its own, while in the `h4` it appears in a media query, so that greater specificity makes the `h4` mixin margin take precedence. 

The solution here is to either move the margin-bottom in `m-notification_message` into a media query equal to what appears in the `h4`, or move the needed styles over from the `h4` and forego the mixin entirely.
