### ISSUE TITLE
More robust section landing pages

### ISSUE THREAD

**Issue by stephanieosan** [cfpb/design-system#860]
## User story
* As a new(ish) user of the Design System, I want an overview of each section that helps me understand what each section covers so that I know where to look for different types of standards. 

---

### Pages this applies to 
* [Foundation](https://cfpb.github.io/design-system/foundation/)
* [Components](https://cfpb.github.io/design-system/components/)
* [Patterns](https://cfpb.github.io/design-system/patterns/)
* [Pages](https://cfpb.github.io/design-system/pages/)
* [Development](https://cfpb.github.io/design-system/development/)
* [Guidelines](https://cfpb.github.io/design-system/guidelines/)

### Background
* Currently each of these landing pages uses the standard template and has a short introductory description of the types of content a user can expect in each section. 
* It would be nice to consider growing these pages to provide more robust overview of the different components
  * We've thought about the potential for these pages to have sort of "visual" browse-able view of all the components in each section

### Work likely involved
* Design discovery around what needs these pages could address and how to best approach those
* Content development
* Design iteration
* Possibly some development work, if the designs require more than what's available in the current template.

**Comment by jenn-franklin** [comment]
This issue was created when we migrated the Design Manual to our current Design System site. During that time, we reviewed all pages to identify potential improvements. As a result, we identified many nice ideas, but the ideas have not been reported by our team's designers or developers as being critical to implement. Because of this, we've decided to close this issue and others in favor of prioritizing issues that have been reported by our designers and developers as being blockers to their work. Thanks!
