### ISSUE TITLE
Legends and labels: Needs content written

### ISSUE THREAD

**Issue by sonnakim** [cfpb/design-system#900]
**Which page is this about?** 
https://cfpb.github.io/design-system/components/labels-and-legends

**What kind of issue is this?**
Add one or more of the issue labels below to the right-hand sidebar AND issue title. 
(We strongly encourage you to make content changes yourself where possible!)
- [ ] Info incorrect 
- [ ] Content enhancement (e.g. confusing or redundant content, small content items need to be added, etc.) 
- [x] Needs content written (page is missing key information, e.g. use cases)
- [ ] Needs code snippet
- [ ] Overhaul page (page needs large-scale content rewriting and restructuring) 
- [ ] Something else (please explain)

**Describe your issue** 
Needs use case info (what is a label? what is a legend? how does it differ from helper text?). This may need some cross-linking with [helper text](https://cfpb.github.io/design-system/components/helper-text) and [fieldsets](https://cfpb.github.io/design-system/components/fieldsets)
 
**Size this request (1=tiny, 5=enormous)**
1  

**Add any additional background info as needed** 
Make sure NOT to include internal links.

***Thanks. Don't forget to add labels indicating issue type and size before submitting!***
***Once you've submitted your issue, please add it to the content backlog project board: https://github.com/cfpb/design-system/projects/1***

**Comment by jenn-franklin** [comment]
This issue was created when we migrated the Design Manual to our current Design System site. During that time, we reviewed all pages to identify potential improvements. As a result, we identified many nice ideas, but the ideas have not been reported by our team's designers or developers as being critical to implement. Because of this, we've decided to close this issue and others in favor of prioritizing issues that have been reported by our designers and developers as being blockers to their work.
