### ISSUE TITLE
Heroes: Needs content written - use cases for photos vs. illustrations

### ISSUE THREAD

**Issue by sonnakim** [cfpb/design-system#908]
**Which page is this about?** 
https://cfpb.github.io/design-system/patterns/heroes#types-1

**What kind of issue is this?**
Add one or more of the issue labels below to the right-hand sidebar AND issue title. 
(We strongly encourage you to make content changes yourself where possible!) 
- Needs content written (page is missing key information, e.g. use cases)

**Describe your issue** 
- Add use case info for when to use photos vs. illustrations

**Size this request (1=tiny, 5=enormous)**
2

**Add any additional background info as needed** 
Make sure NOT to include internal links.

***Thanks. Don't forget to add labels indicating issue type and size before submitting!***
***Once you've submitted your issue, please add it to the content backlog project board: https://github.com/cfpb/design-system/projects/1***

**Comment by jenn-franklin** [comment]
This issue was created when we migrated the Design Manual to our current Design System site. During that time, we reviewed all pages to identify potential improvements. As a result, we identified many nice ideas, but the ideas have not been reported by our team's designers or developers as being critical to implement. Because of this, we've decided to close this issue and others in favor of prioritizing issues that have been reported by our designers and developers as being blockers to their work. Thanks!
