### ISSUE TITLE
Checkboxes: Needs more content

### ISSUE THREAD

**Issue by stephanieosan** [cfpb/design-system#945]
**Which page is this about?** 
[Checkboxes](https://cfpb.github.io/design-system/components/checkboxes)

**Describe your issue** 
* Page lacks any use case information
* Might be nice to have additional content guidelines: for example, what quantity of checkboxes is optimal?

**Comment by jenn-franklin** [comment]
This issue was created when we migrated the Design Manual to our current Design System site. During that time, we reviewed all pages to identify potential improvements. As a result, we identified many nice ideas, but the ideas have not been reported by our team's designers or developers as being critical to implement. Because of this, we've decided to close this issue and others in favor of prioritizing issues that have been reported by our designers and developers as being blockers to their work. 

If we do re-open this issue in the future, let’s consult the [USWDS Checkbox page](https://designsystem.digital.gov/components/checkbox/) for guidance. 

Thanks!
